export const departamentos = [
  'Amazonas',
  'Ancash',
  'Apurimac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Cusco',
  'Huancavelica',
  'Huanuco',
  'Ica',
  'Junin',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martin',
  'Tacna',
  'Tumbes',
  'Ucayali',
];

export const provincias = [
  'Chachapoyas',
  'Bagua',
  'Bongara',
  'Condorcanqui',
  'Luya',
  'Rodriguez de Mendoza',
  'Utcubamba',
  'Huaraz',
  'Aija',
  'Antonio Raymondi',
  'Asuncion',
  'Bolognesi',
  'Carhuaz',
  'Carlos Fermin Fitzca',
  'Casma',
  'Corongo',
  'Huari',
  'Huaylas',
  'Mariscal Luzuriaga',
  'Ocros',
  'Pallasca',
  'Pomabamba',
  'Recuay',
  'Santa',
  'Sihuas',
  'Yungay',
  'Abancay',
  'Andahuaylas',
  'Antabamba',
  'Aymaraes',
  'Cotabambas',
  'Chincheros',
  'Grau',
  'Arequipa',
  'Camana',
  'Caraveli',
  'Castilla',
  'Caylloma',
  'Condesuyos',
  'Islay',
  'La Union',
  'Huamanga',
  'Cangallo',
  'Huanca Sancos',
  'Huanta',
  'La Mar',
  'Lucanas',
  'Parinacochas',
  'Paucar del Sara Sara',
  'Sucre',
  'Victor Fajardo',
  'Vilcas Huaman',
  'Cajamarca',
  'Cajabamba',
  'Celendin',
  'Chota',
  'Contumaza',
  'Cutervo',
  'Hualgayoc',
  'Jaen',
  'San Ignacio',
  'San Marcos',
  'San Miguel',
  'San Pablo',
  'Santa Cruz',
  'Callao',
  'Cusco',
  'Acomayo',
  'Anta',
  'Calca',
  'Canas',
  'Canchis',
  'Chumbivilcas',
  'Espinar',
  'La Convencion',
  'Paruro',
  'Paucartambo',
  'Quispicanchi',
  'Urubamba',
  'Huancavelica',
  'Acobamba',
  'Angaraes',
  'Castrovirreyna',
  'Churcampa',
  'Huaytara',
  'La Mar',
  'Yauli',
  'Junin',
  'Satipo',
  'Tarma',
  'Yauli',
  'Chupaca',
  'Trujillo',
  'Ascope',
  'Bolivar',
  'Chepen',
  'Julcan',
  'Otuzco',
  'Pacasmayo',
  'Pataz',
  'Sanchez Carrion',
  'Santiago de Chuco',
  'Gran Chimu',
  'Viru',
  'Chiclayo',
  'Ferreñafe',
  'Lambayeque',
  'Lima',
  'Barranca',
  'Cajatambo',
  'Canta',
  'Cañete',
  'Huaral',
  'Huarochiri',
  'Huaura',
  'Oyon',
  'Yauyos',
  'Maynas',
  'Alto Amazonas',
  'Loreto',
  'Mariscal Ramon Castilla',
  'Requena',
  'Ucayali',
  'Datem del Marañon',
  'Tambopata',
  'Manu',
  'Tahuamanu',
  'Mariscal Nieto',
  'General Sanchez Cerr',
  'Ilo',
  'Pasco',
  'Daniel Alcides Carri',
  'Oxapampa',
  'Piura',
  'Ayabaca',
  'Huancabamba',
  'Morropon',
  'Paita',
  'Sullana',
  'Talara',
  'Sechura',
  'Puno',
  'Azangaro',
  'Carabaya',
  'Chucuito',
  'El Collao',
  'Huancane',
  'Lampa',
  'Melgar',
  // Se omitieron algunas provincias debido al límite de caracteres del mensaje
];

export const distritos = [
  "Chachapoyas",
  "Asuncion",
  "Balsas",
  "Cheto",
  "Chiliquin",
  "Chuquibamba",
  "Granada",
  "Huancas",
  "La Jalca",
  "Leimebamba",
  "Levanto",
  "Magdalena",
  "Mariscal Castilla",
  "Molinopampa",
  "Montevideo",
  "Olleros",
  "Quinjalca",
  "San Francisco de Daguas",
  "San Isidro de Maino",
  "Soloco",
  "Sonche",
  "Bagua",
  "Aramango",
  "Copallin",
  "El Parco",
  "Imaza",
  "La Peca",
  "Jumbilla",
  "Chisquilla",
  "Churuja",
  "Corosha",
  "Cuispes",
  "Florida",
  "Jazan",
  "Recta",
  "San Carlos",
  "Shipasbamba",
  "Valera",
  "Yambrasbamba",
  "Nieva",
  "El Cenepa",
  "Rio Santiago",
  "Lamud",
  "Camporredondo",
  "Cocabamba",
  "Colcamar",
  "Conila",
  "Inguilpata",
  "Longuita",
  "Lonya Chico",
  "Luya",
  "Luya Viejo",
  "Maria",
  "Ocalli",
  "Ocumal",
  "Pisuquia",
  "Providencia",
  "San Cristobal",
  "San Francisco del Yeso",
  "San Jeronimo",
  "San Juan de Lopecancha",
  "Santa Catalina",
  "Santo Tomas",
  "Tingo",
  "Trita",
  "San Nicolas",
  "Chirimoto",
  "Cochamal",
  "Huambo",
  "Limabamba",
  "Longar",
  "Mariscal Benavides",
  "Milpuc",
  "Omia",
  "Santa Rosa",
  "Totora",
  "Vista Alegre",
  "Bagua Grande",
  "Cajaruro",
  "Cumba",
  "El Milagro",
  "Jamalca",
  "Lonya Grande",
  "Yamon",
  "Huaraz",
  "Cochabamba",
  "Colcabamba",
  "Huanchay",
  "Independencia",
  "Jangas",
  "La Libertad",
  "Olleros",
  "Pampas",
  "Pariacoto",
  "Pira",
  "Tarica",
  "Aija",
  "Coris",
  "Huacllan",
  "La Merced",
  "Succha",
  "Llamellin",
  "Aczo",
  "Chaccho",
  "Chingas",
  "Mirgas",
  "San Juan de Rontoy",
  "Chacas",
  "Acochaca",
  "Chiquian",
  "Abelardo Pardo Lezameta",
  "Antonio Raymondi",
  "Aquia",
  "Cajacay",
  "Canis",
  "Colquioc",
  "Huallanca",
  "Huasta",
  "Huayllacayan",
  "La Primavera",
  "Mangas",
  "Pacllon",
  "San Miguel de Corpanqui",
  "Ticllos",
  "Carhuaz",
  "Acopampa",
  "Amashca",
  "Anta",
  "Ataquero",
  "Marcara",
  "Pariahuanca",
  "San Miguel de Aco",
  "Shilla",
  "Tinco",
  "Yungar",
  "San Luis",
  "San Nicolas",
  "Yauya",
  "Casma",
  "Buena Vista Alta",
  "Comandante Noel",
  "Yautan",
  "Corongo",
  "Aco",
  "Bambas",
  "Cusca",
  "La Pampa",
  "Yanac",
  "Yupan",
  "Huari",
  "Anra",
  "Cajay",
  "Chavin de Huantar",
  "Huacachi",
  "Huacchis",
  "Huachis",
  "Huantar",
  "Masin",
  "Paucas",
  "Ponto",
  "Rahuapampa",
  "Rapayan",
  "San Marcos",
  "San Pedro de Chana",
  "Uco",
  "Huarmey",
  "Cochapeti",
  "Culebras",
  "Huayan",
  "Malvas",
  "Caraz",
  "Huallanca",
  "Huata",
  "Huaylas",
  "Mato",
  "Pamparomas",
  "Pueblo Libre",
  "Santa Cruz",
  "Santo Toribio",
  "Yuracmarca",
  "Piscobamba",
  "Casca",
  "Eleazar Guzman Barron",
  "Fidel Olivas Escudero",
  "Llama",
  "Llumpa",
  "Lucma",
  "Musga",
  "Ocros",
  "Acas",
  "Cajamarquilla",
  "Carhuapampa",
  "Cochas",
  "Congas",
  "Llipa",
  "San Cristobal de Rajan",
  "San Pedro",
  "San Pedro de Huacarpana",
  "Sicsibamba",
  "Sihuas",
  "Acobamba",
  "Alfonso Ugarte",
  "Cashapampa",
  "Chingalpo",
  "Huayllabamba",
  "Quiches",
  "Ragash",
  "San Juan",
  "Sicsibamba",
  "Sihuas",
  "Yungay",
  "Cascapara",
  "Mancos",
  "Matacoto",
  "Quillo",
  "Ranrahirca",
  "Shupluy",
  "Yanama",
  "Yungay",
  "Carhuaz",
  "Acopampa",
  "Amashca",
  "Anta",
  "Ataquero",
  "Marcara",
  "Pariahuanca",
  "San Miguel de Aco",
  "Shilla",
  "Tinco",
  "Yungar",
  "Yungay",
  "Caraz",
  "Huallanca",
  "Huata",
  "Huaylas",
  "Mato",
  "Pamparomas",
  "Pueblo Libre",
  "Santa Cruz",
  "Santo Toribio",
  "Yuracmarca",
  "Piscobamba",
  "Casca",
  "Eleazar Guzman Barron",
  "Fidel Olivas Escudero",
  "Llama",
  "Llumpa",
  "Lucma",
  "Musga",
  "Ocros",
  "Acas",
  "Cajamarquilla",
  "Carhuapampa",
  "Cochas",
  "Congas",
  "Llipa",
  "San Cristobal de Rajan",
  "San Pedro",
  "San Pedro de Huacarpana",
  "Sicsibamba",
  "Sihuas",
  "Acobamba",
  "Alfonso Ugarte",
  "Cashapampa",
  "Chingalpo",
  "Huayllabamba",
  "Quiches",
  "Ragash",
  "San Juan",
  "Sicsibamba",
  "Sihuas",
  "Yungay",
  "Cascapara",
  "Mancos",
  "Matacoto",
  "Quillo",
  "Ranrahirca",
  "Shupluy",
  "Yanama",
  "Yungay",
  "Piscobamba",
  "Casca",
  "Eleazar Guzman Barron",
  "Fidel Olivas Escudero",
  "Llama",
  "Llumpa",
  "Lucma",
  "Musga",
  "Ocros",
  "Acas",
  "Cajamarquilla",
  "Carhuapampa",
  "Cochas",
  "Congas",
  "Llipa",
  "San Cristobal de Rajan",
  "San Pedro",
  "San Pedro de Huacarpana",
  "Sicsibamba",
  "Sihuas",
  "Acobamba",
  "Alfonso Ugarte",
  "Cashapampa",
  "Chingalpo",
  "Huayllabamba",
  "Quiches",
  "Ragash",
  "San Juan",
  "Sicsibamba",
  "Sihuas",
  "Yungay",
  "Cascapara",
  "Mancos",
  "Matacoto",
  "Quillo",
  "Ranrahirca",
  "Shupluy",
  "Yanama",
  "Yungay",
];
